Install dependencies based on target scheme
lafranceinsoumise/ansible-backup pull request #3
Opened 2019-01-21 22:07 UTC by evilhamsterman

This makes the role more flexible by installing only the duplicity dependencies required for your backup targets. This also partially helps with issue #2 because the problem there arises from installing boto for S3 backups. If you aren't doing S3 backups you don't need boto.

2019-01-22 10:34 UTC, jillro requested changes
Hello! Thanks a lot for this contribution :) You changes are great but  you included in the PR a lot of formatting changes / minor changes that are irrelevant to the PR. Can you rebase and keep only the important part ?

2019-01-22 10:34 UTC, guilro commented on .travis.yml
> +  - sudo apt-get install -qq python-apt python-pycurl
Can you remove the formatting changes in formatting that are irrelevant to the Pull Request ?

2019-01-22 10:34 UTC, guilro commented on defaults/main.yml
> +backup_profiles: []
Same :)

2019-01-22 10:34 UTC, guilro commented on templates/pre.j2
Can this be in another pull request ?

2019-01-22 19:14 UTC, evilhamsterman commented
I rebased and removed the requested commits

2019-01-23 10:22 UTC, jillro approved these changes

2019-01-23 10:22 UTC, guilro commented
This has been merged manually, thanks !

2019-01-23 10:22 UTC, closed without merging